version: '3'

services:
  app:
    image: node:10-alpine
    environment:
      NUXT_HOST: 0.0.0.0
    ports:
      - 3000:3000
      - 9005:9005
    working_dir: /app
    volumes:
      - ..:/app
      - ~/.gitconfig:/root/.gitconfig
      - yarn-cache:/usr/local/share/.cache/yarn/
    tty: true

volumes:
  yarn-cache:
